name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 06 * * SUN'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: say hello world
        run: echo hello world
